{% set name = "DeepXDE" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4b56701c01c166d023f1bed707aa698e9cca41ee8fd1a19ca3acd08d00b5fc7c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - numpy
  run:
    - python >=3.7
    - matplotlib-base
    - numpy
    - scikit-learn
    - scikit-optimize
    - scipy

test:
  requires:
    - tensorflow ==2.7.1
    - tensorflow-probability ==0.15.0
    - pytorch
    # - jax
    # - flax
    # - optax
  files:
    - test.py
  commands:
    - export DDEBACKEND=tensorflow.compat.v1
    - python test.py
    - export DDEBACKEND=tensorflow
    - python test.py
    - export DDEBACKEND=pytorch
    - python test.py

about:
  home: https://github.com/lululxvi/deepxde
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: A library for scientific machine learning and physics-informed learning

  description: DeepXDE is a library for scientific machine learning and physics-informed learning.
  doc_url: https://deepxde.readthedocs.io
  dev_url: https://github.com/lululxvi/deepxde

extra:
  recipe-maintainers:
    - lululxvi
