{% set name = "DeepXDE" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2456f4be0cc775d1af619fed5b6cab6ad7f455c5423500067051bf0a93e2657

build:
  number: 0
  # Skip windows with Pytho 2.7 as TensorFlow does not support it well.
  skip: True  # [win and py27]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - matplotlib
    - salib
    - scikit-learn
    - scipy
    - tensorflow

test:
  imports:
    # Skip the import test on Linux as TensorFlow require a more recent
    # version of GLIBC++ than the VM used to build and test package.
    - deepxde  # [not linux]

about:
  home: https://github.com/lululxvi/deepxde
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Deep learning library for solving differential equations'

  description: |
    DeepXDE is a deep learning library for solving differential equations on top of TensorFlow.
    Use DeepXDE if you need a deep learning library that
    solves partial differential equations (PDEs),
    solves integro-differential equations (IDEs),
    solves fractional partial differential equations (fPDEs),
    solves inverse problems for differential equations,
    approximates functions from a dataset with/without constraints,
    and approximates functions from multi-fidelity data.
  doc_url: https://deepxde.readthedocs.io
  dev_url: https://github.com/lululxvi/deepxde

extra:
  recipe-maintainers:
    - lululxvi
