{% set name = "DeepXDE" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e2ee0bd16a539f1bf38a027b4960bc4a951cd61f39f74e87dfeaf367fb9367bc

build:
  number: 0
  # Skip windows with Python 2.7 as TensorFlow does not support it well.
  skip: true  # [win and py27]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - matplotlib-base
    - salib
    - scikit-learn
    - scipy
    # - tensorflow  # [py<38]

test:
  imports:
    # Skip the import test on Linux as TensorFlow require a more recent
    # version of GLIBC++ than the VM used to build and test package.
    # - deepxde  # [not linux and py<38]

about:
  home: https://github.com/lululxvi/deepxde
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Deep learning library for solving differential equations

  description: DeepXDE is a deep learning library for scientific machine learning on top of TensorFlow.
  doc_url: https://deepxde.readthedocs.io
  dev_url: https://github.com/lululxvi/deepxde

extra:
  recipe-maintainers:
    - lululxvi
