{% set name = "DeepXDE" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df395e8220101bb91dd7601e16b9b4a8fc76d8631919cad31c958b8edab8b4f6

build:
  number: 0
  # Skip windows with Python 2.7 as TensorFlow does not support it well.
  skip: true  # [win and py27]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - matplotlib-base
    - salib
    - scikit-learn
    - scipy
    - tensorflow

test:
  imports:
    # Skip the import test on Linux as TensorFlow require a more recent
    # version of GLIBC++ than the VM used to build and test package.
    - deepxde  # [not linux]

about:
  home: https://github.com/lululxvi/deepxde
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Deep learning library for solving differential equations

  description: |
    DeepXDE is a deep learning library for solving differential equations on top of TensorFlow.
    Use DeepXDE if you need a deep learning library that
    solves partial differential equations (PDEs),
    solves integro-differential equations (IDEs),
    solves fractional partial differential equations (fPDEs),
    solves inverse problems for differential equations,
    approximates functions from a dataset with/without constraints,
    approximates functions from multi-fidelity data,
    and approximates operators.
  doc_url: https://deepxde.readthedocs.io
  dev_url: https://github.com/lululxvi/deepxde

extra:
  recipe-maintainers:
    - lululxvi
