{% set name = "DeepXDE" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 65d96ace5da1e785d83905a17a62f9c25ef2dd0735c5af80243000961c808659

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - numpy
  run:
    - python >=3.7
    - numpy
    - matplotlib-base
    - scikit-learn
    - scikit-optimize
    - scipy

test:
  requires:
    - pytorch
    - tensorflow ==2.6.2
    - tensorflow-probability ==0.14.1
  files:
    - test_pytorch.py
    - test_tensorflow.py
  commands:
    - export DDEBACKEND=pytorch
    - python test_pytorch.py
    - export DDEBACKEND=tensorflow
    - python test_tensorflow.py
    - export DDEBACKEND=tensorflow.compat.v1
    - python test_tensorflow.py

about:
  home: https://github.com/lululxvi/deepxde
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: A library for scientific machine learning

  description: DeepXDE is a library for scientific machine learning.
  doc_url: https://deepxde.readthedocs.io
  dev_url: https://github.com/lululxvi/deepxde

extra:
  recipe-maintainers:
    - lululxvi
