{% set name = "DeepXDE" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dbf5cb52c3a25afa3779812d66f8d646c78abf53f5f1bcca410d2c6e377beef8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - numpy
  run:
    - python >=3.7
    - numpy
    - matplotlib-base
    - scikit-learn
    - scikit-optimize
    - scipy

test:
  requires:
    - pytorch
  commands:
    - echo '{"backend": "pytorch"}' > ~/.deepxde/config.json
    - python -c "import deepxde; print(deepxde.__version__)"

about:
  home: https://github.com/lululxvi/deepxde
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: A library for scientific machine learning

  description: DeepXDE is a library for scientific machine learning.
  doc_url: https://deepxde.readthedocs.io
  dev_url: https://github.com/lululxvi/deepxde

extra:
  recipe-maintainers:
    - lululxvi
