{% set name = "DeepXDE" %}
{% set version = "0.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 713259d89c7070426c820f030f4b025b40f38ed99586652ba82a279a8094f0c7

build:
  number: 0
  # Skip windows with Python 2.7 as TensorFlow does not support it well.
  skip: true  # [win and py27]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - matplotlib-base
    - scikit-learn
    - scikit-optimize
    - scipy
    # - tensorflow  # [py<38]

test:
  imports:
    # Skip the import test on Linux as TensorFlow require a more recent
    # version of GLIBC++ than the VM used to build and test package.
    # - deepxde  # [not linux and py<38]

about:
  home: https://github.com/lululxvi/deepxde
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Deep learning library for solving differential equations

  description: DeepXDE is a library for scientific machine learning.
  doc_url: https://deepxde.readthedocs.io
  dev_url: https://github.com/lululxvi/deepxde

extra:
  recipe-maintainers:
    - lululxvi
