{% set name = "DeepXDE" %}
{% set version = "1.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c4280d98f9b086ad8853cf8c49cfcc090b9cb1e6318f3af17442c70cd47c70b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
    - numpy
  run:
    - python >=3.9
    - matplotlib-base
    - numpy
    - scikit-learn
    - scikit-optimize
    - scipy

test:
  requires:
    - tensorflow ==2.14
    - tensorflow-probability ==0.22
    - pytorch
    # - jax
    # - flax
    # - optax
  files:
    - test.py
  commands:
    - export DDEBACKEND=tensorflow.compat.v1
    - python test.py
    - export DDEBACKEND=tensorflow
    - python test.py
    - export DDEBACKEND=pytorch
    - python test.py

about:
  home: https://github.com/lululxvi/deepxde
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: A library for scientific machine learning and physics-informed learning

  description: DeepXDE is a library for scientific machine learning and physics-informed learning.
  doc_url: https://deepxde.readthedocs.io
  dev_url: https://github.com/lululxvi/deepxde

extra:
  recipe-maintainers:
    - lululxvi
