{% set name = "deepxde" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cfd819a92a546efc1c52f28490c14e9de28ff2bce6f6489d1402bc0dda8b0374

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
    - numpy
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - scikit-learn
    - scikit-optimize
    - scipy

test:
  requires:
    - tensorflow ==2.14
    - tensorflow-probability ==0.22
    - pytorch
    # - jax
    # - flax
    # - optax
    - python {{ python_min }}
  files:
    - test.py
  commands:
    - export DDEBACKEND=tensorflow.compat.v1
    - python test.py
    - export DDEBACKEND=tensorflow
    - python test.py
    - export DDEBACKEND=pytorch
    - python test.py

about:
  home: https://github.com/lululxvi/deepxde
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: A library for scientific machine learning and physics-informed learning

  description: DeepXDE is a library for scientific machine learning and physics-informed learning.
  doc_url: https://deepxde.readthedocs.io
  dev_url: https://github.com/lululxvi/deepxde

extra:
  recipe-maintainers:
    - lululxvi
