{% set name = "DeepXDE" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 18522714e2fa130ad3eee92bfc8eaedd2d9fe1d3a7143e320c2b45fc160c7126

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - numpy
  run:
    - python >=3.7
    - matplotlib-base
    - numpy
    - scikit-learn
    - scikit-optimize
    - scipy

test:
  requires:
    - pytorch
    - tensorflow ==2.7.1
    - tensorflow-probability ==0.15.0
  files:
    - test_tensorflow.py
    - test_pytorch.py
  commands:
    - export DDEBACKEND=tensorflow.compat.v1
    - python test_tensorflow.py
    # - export DDEBACKEND=tensorflow  # The platform host doesn't support XLA
    # - python test_tensorflow.py
    - export DDEBACKEND=pytorch
    - python test_pytorch.py

about:
  home: https://github.com/lululxvi/deepxde
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: A library for scientific machine learning and physics-informed learning

  description: DeepXDE is a library for scientific machine learning and physics-informed learning.
  doc_url: https://deepxde.readthedocs.io
  dev_url: https://github.com/lululxvi/deepxde

extra:
  recipe-maintainers:
    - lululxvi
