{% set name = "DeepXDE" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4478aaf7eb0d497b1ff493c5643f23e36e02878edbc936e676dda50ff50f91a7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - numpy
  run:
    - python >=3.7
    - numpy
    - matplotlib-base
    - scikit-learn
    - scikit-optimize
    - scipy

test:
  requires:
    - pytorch
    - tensorflow >=2.6.0
    - tensorflow-probability
  files:
    - test_pytorch.py
    - test_tensorflow.py
  commands:
    - export DDEBACKEND=pytorch
    - python -c "import deepxde; print(deepxde.__version__)"
    - python test_pytorch.py
    - export DDEBACKEND=tensorflow
    - python test_tensorflow.py
    - export DDEBACKEND=tensorflow.compat.v1
    - python test_tensorflow.py

about:
  home: https://github.com/lululxvi/deepxde
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: A library for scientific machine learning

  description: DeepXDE is a library for scientific machine learning.
  doc_url: https://deepxde.readthedocs.io
  dev_url: https://github.com/lululxvi/deepxde

extra:
  recipe-maintainers:
    - lululxvi
