travis:
  secure:
    BINSTAR_TOKEN: Rk0XI32TpInibXdJfTynFWj/PVR8qx84l5rEhoNhb0VPP35KMtlxT+5lvD0yMiDhpCB2qftnXNffTeOWRZGcsgA5LNoWVXIb8H7KS8sTjvTMa5mjno9E3FlBHKu83hnlozbNnKWqt4XBtBtkaiftUy88l9CI0VYdL9JVsHZtnSqyqMfbyQK2p+7YmQ0ozuS3WYq0BP2qiraKTzYnrlJamWOmN2VgtVoF6OsE86YUWXyZYhGyJdtvc9GqDaB+PQNDw0TYajihY1ngQojP6O1DCE4XlJG+csW7VkdVWUuM7yKPTapSi2u6vtwiaV+tDCdeBFWaiRaAouXj6nrE/lLn/WMP2Q7zsDDvstix5szX+qJssE5GbTqGk98Sqv9rcGzyEaFf/UudNofyFFTPqJf9KgpzuDoYWw/SCX9DsRLaOrrNbsUT3og3wYs80VYlrJaqtQ1pOagVZonzfey+sTFrcXCWAL1668l/5neJwM5C5jHxob0XcLSUKAktdyQnW3oUjCzvI9nerNAAdWWMBIuY+/qiM4wcO1cv1LnVGh3hzM1z6gtrBIKOJ4Pfmpb2rJL95v++TI6VbqeBi8nbKJE0dlFcruEp0+Fs3/9z9bU1b0zV5l3IsXNqY7tOXrxHOKJReiLPo6YAgPAsPqkP0z5XmtSGsVtcTCKwVqXE53Cfkuw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
